#############################################################################
# Makefile for building: suplayer
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  suplayer.pro
# Template: app
# Command: /home/blacknc/Bin/Qt5.3.1/5.3/gcc/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile suplayer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/linux-g++ -I. -I../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include -I../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets -I../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui -I../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/blacknc/Bin/Qt5.3.1/5.3/gcc -Wl,-rpath,/home/blacknc/Bin/Qt5.3.1/5.3/gcc/lib
LIBS          = $(SUBLIBS) -L/home/blacknc/Bin/Qt5.3.1/5.3/gcc/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/blacknc/Bin/Qt5.3.1/5.3/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		child.cpp qrc_resours.cpp \
		moc_mainwindow.cpp \
		moc_child.cpp
OBJECTS       = main.o \
		mainwindow.o \
		child.o \
		qrc_resours.o \
		moc_mainwindow.o \
		moc_child.o
DIST          = ../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/spec_pre.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/shell-unix.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/unix.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/linux.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/g++-base.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/g++-unix.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/qconfig.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/qt_functions.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/qt_config.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/spec_post.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/default_pre.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/resolve_config.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/default_post.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/warn_on.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/qt.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/resources.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/moc.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/unix/opengl.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/uic.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/unix/thread.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/testcase_targets.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/exceptions.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/yacc.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/lex.prf \
		suplayer.pro main.cpp \
		mainwindow.cpp \
		child.cpp
QMAKE_TARGET  = suplayer
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = suplayer


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: suplayer.pro ../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf ../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/spec_pre.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/shell-unix.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/unix.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/linux.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/g++-base.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/g++-unix.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/qconfig.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/qt_functions.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/qt_config.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/spec_post.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/default_pre.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/resolve_config.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/default_post.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/warn_on.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/qt.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/resources.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/moc.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/unix/opengl.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/uic.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/unix/thread.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/testcase_targets.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/exceptions.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/yacc.prf \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/lex.prf \
		suplayer.pro \
		resours.qrc \
		/home/blacknc/Bin/Qt5.3.1/5.3/gcc/lib/libQt5Widgets.prl \
		/home/blacknc/Bin/Qt5.3.1/5.3/gcc/lib/libQt5Gui.prl \
		/home/blacknc/Bin/Qt5.3.1/5.3/gcc/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile suplayer.pro
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/spec_pre.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/shell-unix.conf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/unix.conf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/linux.conf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base.conf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/gcc-base-unix.conf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/g++-base.conf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/common/g++-unix.conf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/qconfig.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/qt_functions.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/qt_config.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/linux-g++/qmake.conf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/spec_post.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/exclusive_builds.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/default_pre.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/resolve_config.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/default_post.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/warn_on.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/qt.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/resources.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/moc.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/unix/opengl.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/uic.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/unix/thread.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/testcase_targets.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/exceptions.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/yacc.prf:
../../../blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/features/lex.prf:
suplayer.pro:
resours.qrc:
/home/blacknc/Bin/Qt5.3.1/5.3/gcc/lib/libQt5Widgets.prl:
/home/blacknc/Bin/Qt5.3.1/5.3/gcc/lib/libQt5Gui.prl:
/home/blacknc/Bin/Qt5.3.1/5.3/gcc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile suplayer.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/suplayer1.0.0 || mkdir -p .tmp/suplayer1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/suplayer1.0.0/ && $(COPY_FILE) --parents resours.qrc .tmp/suplayer1.0.0/ && $(COPY_FILE) --parents mainwindow.h child.h .tmp/suplayer1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp child.cpp .tmp/suplayer1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/suplayer1.0.0/ && (cd `dirname .tmp/suplayer1.0.0` && $(TAR) suplayer1.0.0.tar suplayer1.0.0 && $(COMPRESS) suplayer1.0.0.tar) && $(MOVE) `dirname .tmp/suplayer1.0.0`/suplayer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/suplayer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_resours.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resours.cpp
qrc_resours.cpp: resours.qrc \
		ico/signal.png \
		ico/mute.png \
		ico/open.png \
		ico/random.png \
		ico/pause.png \
		ico/prev.png \
		ico/delete.png \
		ico/del.png \
		ico/onelist.png \
		ico/savelst.png \
		ico/suwin.gif \
		ico/looplst.png \
		ico/ground.jpg \
		ico/add.png \
		ico/start.png \
		ico/backward.png \
		ico/3.jpg \
		ico/loop.png \
		ico/ply.png \
		ico/next.png \
		ico/lodelst.png \
		ico/speaker.png \
		ico/full.png \
		ico/stop.png \
		ico/forward.png
	/home/blacknc/Bin/Qt5.3.1/5.3/gcc/bin/rcc -name resours resours.qrc -o qrc_resours.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_child.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_child.cpp
moc_mainwindow.cpp: ../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QMainWindow \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qmainwindow.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qwidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpalette.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qcursor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qtabwidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qicon.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QRect \
		child.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QDialog \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qdialog.h \
		mainwindow.h
	/home/blacknc/Bin/Qt5.3.1/5.3/gcc/bin/moc $(DEFINES) -I/home/blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/linux-g++ -I/home/code/qt/suplayer -I/home/blacknc/Bin/Qt5.3.1/5.3/gcc/include -I/home/blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets -I/home/blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui -I/home/blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore mainwindow.h -o moc_mainwindow.cpp

moc_child.cpp: ../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QDialog \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qdialog.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qwidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpalette.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qcursor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		child.h
	/home/blacknc/Bin/Qt5.3.1/5.3/gcc/bin/moc $(DEFINES) -I/home/blacknc/Bin/Qt5.3.1/5.3/gcc/mkspecs/linux-g++ -I/home/code/qt/suplayer -I/home/blacknc/Bin/Qt5.3.1/5.3/gcc/include -I/home/blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets -I/home/blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui -I/home/blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore child.h -o moc_child.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/blacknc/Bin/Qt5.3.1/5.3/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QMainWindow \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qmainwindow.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qwidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpalette.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qcursor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qtabwidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qicon.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QRect \
		child.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QDialog \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qdialog.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QApplication \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qapplication.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcoreapplication.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qeventloop.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qdesktopwidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qguiapplication.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QMainWindow \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qmainwindow.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qwidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpalette.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qcursor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qtabwidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qicon.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QRect \
		child.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QDialog \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qdialog.h \
		ui_mainwindow.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QVariant \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QAction \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qaction.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qactiongroup.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QApplication \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qapplication.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcoreapplication.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qeventloop.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qdesktopwidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qguiapplication.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qinputmethod.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QButtonGroup \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qbuttongroup.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QDockWidget \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qdockwidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QGridLayout \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qgridlayout.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qlayout.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qlayoutitem.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qboxlayout.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QHBoxLayout \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QHeaderView \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qheaderview.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qabstractitemview.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qabstractscrollarea.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qframe.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qabstractitemmodel.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qitemselectionmodel.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qabstractitemdelegate.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qstyleoption.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qabstractspinbox.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qvalidator.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qregularexpression.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qslider.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qabstractslider.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qstyle.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qtabbar.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qrubberband.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QLabel \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qlabel.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QMenu \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qmenu.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QMenuBar \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qmenubar.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QPushButton \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qpushbutton.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qabstractbutton.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QSlider \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QSpacerItem \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QStatusBar \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qstatusbar.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QTableWidget \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qtablewidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qtableview.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QToolBar \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qtoolbar.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QVBoxLayout \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QWidget \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QDesktopWidget \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QProcess \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qprocess.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QStringList \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QTableWidgetItem \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QFileDialog \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qfiledialog.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qdir.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfileinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QDebug \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QString \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QTimerEvent \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QTimer \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtimer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qbasictimer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/QPalette \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/QKeyEvent \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QByteArray \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/QIcon \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/QSize \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QLineEdit \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qlineedit.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtextcursor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtextformat.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpen.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtextoption.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/QPixmap \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/QBrush \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/QBitmap \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qbitmap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QMessageBox \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

child.o: child.cpp child.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QDialog \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qdialog.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qwidget.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qglobal.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qconfig.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfeatures.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsystemdetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qprocessordetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcompilerdetection.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtypeinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtypetraits.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsysinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlogging.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qflags.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qbasicatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qgenericatomic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_msvc.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv7.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv6.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_armv5.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_ia64.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_mips.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_x86.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_gcc.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qatomic_unix.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qglobalstatic.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmutex.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qnumeric.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qnamespace.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobject.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstring.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qchar.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qbytearray.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qrefcount.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qarraydata.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringbuilder.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlist.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qalgorithms.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qiterator.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcoreevent.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qscopedpointer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmetatype.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvarlengtharray.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcontainerfwd.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qisenum.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qobject_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmargins.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpaintdevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qrect.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsize.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qpoint.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpalette.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qcolor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qrgb.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringlist.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qdatastream.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qiodevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qpair.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qregexp.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qstringmatcher.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qbrush.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvector.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qmatrix.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpolygon.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qregion.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qline.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtransform.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpainterpath.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qimage.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpixmap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qshareddata.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qhash.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfont.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfontmetrics.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qfontinfo.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qcursor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qkeysequence.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qevent.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qvariant.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qmap.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qdebug.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qtextstream.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qlocale.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qset.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qcontiguouscache.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qurl.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qurlquery.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfile.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtCore/qfiledevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qvector2d.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtouchdevice.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QPushButton \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qpushbutton.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qabstractbutton.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qicon.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QLabel \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qlabel.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qframe.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QLineEdit \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qlineedit.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtextcursor.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtextformat.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qpen.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtGui/qtextoption.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/QHBoxLayout \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qboxlayout.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qlayout.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qlayoutitem.h \
		../../../blacknc/Bin/Qt5.3.1/5.3/gcc/include/QtWidgets/qgridlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o child.o child.cpp

qrc_resours.o: qrc_resours.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resours.o qrc_resours.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_child.o: moc_child.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_child.o moc_child.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

